name: superpoint
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python=3.8
  - pytorch::pytorch=2.2.2
  - pytorch::torchvision=0.17.2
  - pytorch-cuda=12.1
  - conda-forge::imageio
  - conda-forge::tensorboardx
  - conda-forge::opencv
  - conda-forge::matplotlib
  - conda-forge::pydantic
  - tqdm
  - pip
  - pip:
    - coloredlogs
    - termcolor
    - imgaug
